
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-program-options-dev libboost-date-time-dev libboost-signals-dev libboost-system-dev libboost-filesystem-dev libboost-thread-dev libqt4-dev swig python-all-dev
script:
    - mkdir -p build && (cd build && cmake .. && make)