
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-program-options1.48-dev libboost-date-time1.48-dev libboost-signals1.48-dev libboost-system1.48-dev libboost-filesystem1.48-dev libboost-thread1.48-dev libqt4-dev swig python-all-dev
script:
    - mkdir -p build && (cd build && cmake .. && make)